### ISSUE TITLE
can you share notion url?

### ISSUE THREAD

**Issue by umut77** [YJack0000/nuxt-notion-blog#12]
Can you please share the table url in notion, seems like there is a slight issue with tables.
Thank you

**Comment by YJack0000** [comment]
The whole table is as shown below. 
But because there are some unpublished things in it, it is inconvenient to set it as public. 
Can you explain a little bit about the problem? 
![Screenshot 2023-08-23 at 6 29 03 PM](https://github.com/YJack0000/nuxt-notion-blog/assets/49984479/afba05bf-a0fc-42a0-a92a-721904baf74c)

**Comment by umut77** [comment]
Thank you so much I figured out , I set up the table property names without capital letter and was giving me an error but all fixed now, I tried to add 2 things,
1) instead of using ID with post url we can create a slug and point the url 
2) Add a thumbnail 
![Screenshot 2023-08-23 at 2 20 28 PM](https://github.com/YJack0000/nuxt-notion-blog/assets/977663/d69c3dd8-7087-4abb-873c-9cd421321a44)

**Comment by YJack0000** [comment]
Cool!

Regarding the original project [nuxt-3-notion-blog](https://github.com/egrzeszczak/nuxt-3-notion-blog), I noticed that the author has implemented the thumbnail feature. However, I'm looking for a more streamlined approach since I'd prefer not to spend time creating thumbnails. 😅

It would be great if you could suggest a way to modularize the thumbnail feature, making it an optional component that users can easily add or remove. Your assistance would be much appreciated!

**Comment by umut77** [comment]
ok so I managed to add thumbnail feature; 

1) Add a new property in Notion ; Thumbnail and type is Files&Media
2) Open types>notion.d.ts 
3) Add the code below in Properties section;
  `Thumbnail: {
      title: {}
      files: Array
    }`

4) Open PostSmall.vue and insert 
`<div v-for="thumbnail in post.properties.Thumbnail.files" class="umut">
      <img
        :src="`${thumbnail.file.url}`"
        class="object-cover object-center h-44 w-96"
      />
    </div>`

<img width="1331" alt="Screenshot 2023-08-23 at 3 17 34 PM" src="https://github.com/YJack0000/nuxt-notion-blog/assets/977663/0dd8886e-dfaa-4941-8151-f8e4f47a6cf5">

**Comment by umut77** [comment]
> Cool!
> 
> Regarding the original project [nuxt-3-notion-blog](https://github.com/egrzeszczak/nuxt-3-notion-blog), the author has implemented the thumbnail feature. However, I'm looking for a more streamlined approach since I'd prefer not to spend time creating thumbnails for my posts. 😅
> 
> It would be great if you could suggest a way to modularize the thumbnail feature, making it an optional component that users can easily add or remove. Your assistance would be much appreciated!

can be easily done with config file, will contribute with that!
